---
- name: MySQL installation
  apt:
    pkg:
      - mysql-server
      - mysql-client
      - python3-mysqldb
      - libmysqlclient-dev
    update_cache: yes

- name: User creation
  mysql_user:
    name: '{{ mysql.username }}'
    password: '{{ mysql.password }}'
    priv: '*.*:ALL'
    host: '%'
    state: present

- name: Database creation
  mysql_db:
    name: '{{ mysql.db_name }}'
    state: present
